include ../include_top.mac

INCLUDES   = ${INCLUDES_COMMON}
CFLAGS     = ${CFLAGS_COMMON} ${INCLUDES} -DNDEBUG
LDFLAGS    = ${LDFLAGS_COMMON}
EXECUTABLE = ../../bin/svgToPoly

SOURCES    = svgToPoly.cpp

include ../include_bottom.mk
