include ../include_top.mac

INCLUDES   = ${INCLUDES_COMMON}
CFLAGS     = ${CFLAGS_COMMON} ${INCLUDES} -DNDEBUG -DGL_SILENCE_DEPRECATION
LDFLAGS    = ${LDFLAGS_COMMON}
EXECUTABLE = ../../bin/simulator

SOURCES    = simulator.cpp \
						 ../../src/Hyperelastic/STVK.cpp \
						 ../../src/Timestepper/TIMESTEPPER.cpp \
						 ../../src/Timestepper/FORWARD_EULER.cpp \
						 ../../src/Geometry/SQUARE.cpp \
						 ../../src/Geometry/TRIANGLE_MESH.cpp 

include ../include_bottom.mk
